In [18]:
import pandas as pd

sales = pd.read_csv('sales_subset.csv')
sales_1_1 = sales[(sales['department'] == 1) & (sales['store'] == 1)]
print(sales.head())
print(sales_1_1)

   Unnamed: 0  store type  department        date  weekly_sales  is_holiday  \
0           0      1    A           1  2010-02-05      24924.50       False
1           1      1    A           1  2010-03-05      21827.90       False
2           2      1    A           1  2010-04-02      57258.43       False
3           3      1    A           1  2010-05-07      17413.94       False
4           4      1    A           1  2010-06-04      17558.09       False

   temperature_c  fuel_price_usd_per_l  unemployment
0       5.727778              0.679451         8.106
1       8.055556              0.693452         8.106
2      16.816667              0.718284         7.808
3      22.527778              0.748928         7.808
4      27.050000              0.714586         7.808
    Unnamed: 0  store type  department        date  weekly_sales  is_holiday  \
0            0      1    A           1  2010-02-05      24924.50       False
1            1      1    A           1  2010-03-05      21827.90       False
2            2      1    A           1  2010-04-02      57258.43       False
3            3      1    A           1  2010-05-07      17413.94       False
4            4      1    A           1  2010-06-04      17558.09       False
5            5      1    A           1  2010-07-02      16333.14       False
6            6      1    A           1  2010-08-06      17508.41       False
7            7      1    A           1  2010-09-03      16241.78       False
8            8      1    A           1  2010-10-01      20094.19       False
9            9      1    A           1  2010-11-05      34238.88       False
10          10      1    A           1  2010-12-03      22517.56       False
11          11      1    A           1  2011-01-07      15984.24       False

    temperature_c  fuel_price_usd_per_l  unemployment
0        5.727778              0.679451         8.106
1        8.055556              0.693452         8.106
2       16.816667              0.718284         7.808
3       22.527778              0.748928         7.808
4       27.050000              0.714586         7.808
5       27.172222              0.705076         7.787
6       30.644444              0.693980         7.787
7       27.338889              0.680772         7.787
8       22.161111              0.687640         7.838
9       14.855556              0.710359         7.838
10       9.594444              0.715378         7.838
11       9.038889              0.786176         7.742

In [ ]:
#                                 STATISTICS WITH PANDAS
#########################################################

#                  SUMMARY STATISTICS

# find the mean
# dogs['height_cm'].mean()

# can also use the following:
# .median(), .mode(), .min(), .max(), .var(), .std(), .sum(), .quantile()

# statistics for dates
# dogs['date_of_birth'].min()

# the .agg() method allows custom summary statistics
# def pct30(column):
#    return column.quantile(0.3)

# def pct40(column):
#    return column.quantile(0.4)

# dogs['weight_kg'].agg(pct30)    will return the 30th quantile of dog weights
# dogs[['weight_kg', [height_cm']].agg(pct30) will return 30th quantile for both 
# dogs['weight_kg'].agg([pct30,pct40])   will return both 30th and 40th quantile for dog weight

# cumulative sum
# dogs['weight_kg'].cumsum()          will return a list of cumulative dog weights

# can also use .cummax(), .cummin(), .cumprod()

In [19]:
#                       Summary Statistics Problems

#Explore your new DataFrame first by printing the first few rows of the sales DataFrame.
print(sales.head())

#Print information about the columns in sales.
print(sales.info())

#Print the mean of the weekly_sales column.
print(sales['weekly_sales'].mean())

#Print the median of the weekly_sales column.
print(sales['weekly_sales'].median())

# Print the maximum of the date column.
print(sales['date'].max())

# Print the minimum of the date column.
print(sales['date'].min())


# A custom IQR function
def iqr(column):
    return column.quantile(0.75) - column.quantile(0.25)
    
# Use the custom iqr function defined for you along with .agg() to print the IQR of the temperature_c column of sales.
print(sales['temperature_c'].agg(iqr))

# Update the column selection to use the custom iqr function with .agg() to print the IQR of temperature_c, fuel_price_usd_per_l, and unemployment, in that order.
print(sales[['temperature_c', 'fuel_price_usd_per_l','unemployment']].agg(iqr))


# Update the aggregation functions called by .agg(): include iqr and "median" in that order.
print(sales[['temperature_c', 'fuel_price_usd_per_l','unemployment']].agg([iqr,'median']))

#Sort the rows of sales_1_1 by the date column in ascending order.
sales_1_1 = sales_1_1.sort_values('date')

#Get the cumulative sum of weekly_sales and add it as a new column of sales_1_1 called cum_weekly_sales.
sales_1_1['cum_weekly_sales'] = sales_1_1['weekly_sales'].cumsum()


#Get the cumulative maximum of weekly_sales, and add it as a column called cum_max_sales.
sales_1_1['cum_max_sales'] = sales_1_1['weekly_sales'].cummax()


# Print the date, weekly_sales, cum_weekly_sales, and cum_max_sales columns.
print(sales_1_1[['date', 'weekly_sales', 'cum_weekly_sales', 'cum_max_sales']])

   Unnamed: 0  store type  department        date  weekly_sales  is_holiday  \
0           0      1    A           1  2010-02-05      24924.50       False
1           1      1    A           1  2010-03-05      21827.90       False
2           2      1    A           1  2010-04-02      57258.43       False
3           3      1    A           1  2010-05-07      17413.94       False
4           4      1    A           1  2010-06-04      17558.09       False

   temperature_c  fuel_price_usd_per_l  unemployment
0       5.727778              0.679451         8.106
1       8.055556              0.693452         8.106
2      16.816667              0.718284         7.808
3      22.527778              0.748928         7.808
4      27.050000              0.714586         7.808
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10774 entries, 0 to 10773
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            10774 non-null  int64
 1   store                 10774 non-null  int64
 2   type                  10774 non-null  object
 3   department            10774 non-null  int64
 4   date                  10774 non-null  object
 5   weekly_sales          10774 non-null  float64
 6   is_holiday            10774 non-null  bool
 7   temperature_c         10774 non-null  float64
 8   fuel_price_usd_per_l  10774 non-null  float64
 9   unemployment          10774 non-null  float64
dtypes: bool(1), float64(4), int64(3), object(2)
memory usage: 768.2+ KB
None
23843.95014850566
12049.064999999999
2012-10-26
2010-02-05
16.583333333333336
temperature_c           16.583333
fuel_price_usd_per_l     0.073176
unemployment             0.565000
dtype: float64
        temperature_c  fuel_price_usd_per_l  unemployment
iqr         16.583333              0.073176         0.565
median      16.966667              0.743381         8.099
          date  weekly_sales  cum_weekly_sales  cum_max_sales
0   2010-02-05      24924.50          24924.50       24924.50
1   2010-03-05      21827.90          46752.40       24924.50
2   2010-04-02      57258.43         104010.83       57258.43
3   2010-05-07      17413.94         121424.77       57258.43
4   2010-06-04      17558.09         138982.86       57258.43
5   2010-07-02      16333.14         155316.00       57258.43
6   2010-08-06      17508.41         172824.41       57258.43
7   2010-09-03      16241.78         189066.19       57258.43
8   2010-10-01      20094.19         209160.38       57258.43
9   2010-11-05      34238.88         243399.26       57258.43
10  2010-12-03      22517.56         265916.82       57258.43
11  2011-01-07      15984.24         281901.06       57258.43